services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=axonetest
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.ml.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2g

  kibana:
    image: kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=axonetest
      - xpack.ml.enabled=false
      - NODE_OPTIONS="--max-old-space-size=1024"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk
    volumes:
      - ./kibana-logo:/usr/share/kibana/src/core/server/core_app/assets/logos
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1g

  logstash:
    image: logstash:8.15.0
    container_name: logstash
    environment:
      - ELASTIC_PASSWORD=axonetest
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=axonetest
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/data:/usr/share/logstash/data
    depends_on:
      - elasticsearch
      - fastapi-endpoint
    networks:
      - elk
    restart: on-failure
    user: "0:0"

  fastapi-endpoint:
    container_name: fastapi-endpoint
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - elk

volumes:
  es_data:

networks:
  elk:
    driver: bridge
